<?php

namespace Database\Seeders;

use App\Models\GroupOpinion;
use App\Models\Member;
use App\Models\Nominee;
use App\Models\Share;
use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;

class MemberSeeder extends Seeder
{
    public function run(): void
    {
        $members = [
            [
                'full_name'         => 'Md. Hasanur Rashid',
                'shares'            => 1,
                'email'             => 'hkjinius@gmail.com',
                'permanent_address' => 'Tantipara, Magura',
                'present_address'   => 'Abdullahpur, South Keraniganj, Dhaka',
                'phone'             => '01675472498',
                'profession'        => 'Marketing Executive',
                'company_name'      => 'Coca-Cola Beverages Ltd Bangladesh',
                'company_address'   => 'Navana HR Tower, Gulshan-1',
                'nominee_name'      => 'Jesmin Rashid',
                'relationship'      => 'Mother',
                'nominee_mobile'    => '01731922890',
                'nominee_address'   => 'Tantipara, Magura',
                'opinion'           => null,
                'suggestion'        => null,
            ],
            [
                'full_name'         => 'Salauddin Ahmad',
                'shares'            => 1,
                'email'             => 'salauddinacca@gmail.com',
                'permanent_address' => 'PTI Para Grosthan Road Magura',
                'present_address'   => 'PTI Para Grosthan Road Magura',
                'phone'             => '01670713372',
                'profession'        => 'Job',
                'company_name'      => 'Ha-Meem Group',
                'company_address'   => 'Tongi, Nishad Nagar, Gazipur',
                'nominee_name'      => 'Yesmin Akhter Anny',
                'relationship'      => 'Wife',
                'nominee_mobile'    => '01841978881',
                'nominee_address'   => 'PTI Para Grosthan Road Magura',
                'opinion'           => null,
                'suggestion'        => null,
            ],
            [
                'full_name'         => 'MD Sharear Ferdush Sarzu',
                'shares'            => 2,
                'email'             => 's.t.sarzu@gmail.com',
                'permanent_address' => 'Sayed ator Ali road, kader building magura',
                'present_address'   => 'Sayed ator Ali road, kader building magura',
                'phone'             => '01757801601',
                'profession'        => 'Banker',
                'company_name'      => 'Sbac bank plc',
                'company_address'   => '2&3 rajuk avenue bsc tower motijheel',
                'nominee_name'      => 'Muhammad Al Fatih Saad',
                'relationship'      => 'Son',
                'nominee_mobile'    => '01629011824',
                'nominee_address'   => 'Sayed ator Ali road, kader building magura',
                'opinion'           => 'Ok',
                'suggestion'        => null,
            ],
            [
                'full_name'         => 'Md Tanvir Ul Haque Sajal',
                'shares'            => 2,
                'email'             => 't.haque.ju@gmail.com',
                'permanent_address' => 'Magura councilpara m, r road, magura sadar',
                'present_address'   => 'Japan, Chiba Mihama',
                'phone'             => '09044118535',
                'profession'        => 'Kamla',
                'company_name'      => 'Bidesh',
                'company_address'   => 'Japan',
                'nominee_name'      => 'Arifa Nusrat',
                'relationship'      => 'Wife',
                'nominee_mobile'    => 'N/A',
                'nominee_address'   => 'Magura councilpara m, r road, magura sadar',
                'opinion'           => 'valo',
                'suggestion'        => 'obossoi',
            ],
            [
                'full_name'         => 'Akibuzzaman Rubel',
                'shares'            => 2,
                'email'             => 'fafrubel@gmail.com',
                'permanent_address' => 'Parnanduali Purba Munshipara, Magura Sadar',
                'present_address'   => 'Parnanduali Purba Munshipara, Magura Sadar',
                'phone'             => '01316414149',
                'profession'        => 'Private Service (Private Bank)',
                'company_name'      => 'Southeast Bank PLC',
                'company_address'   => 'Rajbari Branch Rajbari',
                'nominee_name'      => 'Masura Akter',
                'relationship'      => 'Spouse',
                'nominee_mobile'    => '01602888127',
                'nominee_address'   => 'Pernanduali Purba Munshipara, Magura',
                'opinion'           => 'Very Good',
                'suggestion'        => null,
            ],
            [
                'full_name'         => 'Md. Rakibul Islam',
                'shares'            => 1,
                'email'             => 'rakibul031islam@gmail.com',
                'permanent_address' => '30, Islampur para, Magura sadar, Magura',
                'present_address'   => '40, Sha Ali Bag, Mirpur-1, Dhaka-1216',
                'phone'             => '01754361014',
                'profession'        => 'Advocate',
                'company_name'      => 'Akij Group',
                'company_address'   => '198, Akij House, Gulshan Link Road, Dhaka-1208',
                'nominee_name'      => 'Nazma Alam',
                'relationship'      => 'Mother',
                'nominee_mobile'    => '01754361014',
                'nominee_address'   => '30, Islampur para, Magura sadar, Magura',
                'opinion'           => null,
                'suggestion'        => null,
            ],
            [
                'full_name'         => 'MD. Lincon Hasan',
                'shares'            => 1,
                'email'             => 'lincon.eteruet@gmail.com',
                'permanent_address' => 'Derua, Magura Sadar, Magura',
                'present_address'   => 'Rupatoli R/A, Barisal Sadar, Barisal',
                'phone'             => '01738143388',
                'profession'        => 'Assistant Manager (Electronics)',
                'company_name'      => 'BAPEX, Petrobangla',
                'company_address'   => 'Karwan Bazar, Dhaka',
                'nominee_name'      => 'Anamika Ferdous',
                'relationship'      => 'Spouse',
                'nominee_mobile'    => '01764652981',
                'nominee_address'   => 'Adarsha Para, Magura Sadar, Magura',
                'opinion'           => 'N/A',
                'suggestion'        => 'N/A',
            ],
            [
                'full_name'         => 'S. M. Saklain',
                'shares'            => 1,
                'email'             => 'lionporag@gmail.com',
                'permanent_address' => 'H# 206/2, R#91/1, Stadium Poschim Para, Magura',
                'present_address'   => 'H#558, R#31, Goran Chapra Masjid, Khilgaon, Dhaka',
                'phone'             => '01744307992',
                'profession'        => 'Banker',
                'company_name'      => 'Trust Bank PLC',
                'company_address'   => 'Sadarghat Branch, Dhaka',
                'nominee_name'      => 'Fatema Khatun Rajoni',
                'relationship'      => 'Wife',
                'nominee_mobile'    => '01740730464',
                'nominee_address'   => 'H#558, R#31, Goran Chapra Masjid, Khilgaon, Dhaka',
                'opinion'           => 'Allah will help us.',
                'suggestion'        => 'United we stand.',
            ],
            [
                'full_name'         => 'Sujon Kumar Biswas',
                'shares'            => 1,
                'email'             => 'sujanbiswaseee11@gmail.com',
                'permanent_address' => 'Sreekundi, Magura',
                'present_address'   => 'Salgaria, Pabna',
                'phone'             => '01747607676',
                'profession'        => 'Private service',
                'company_name'      => 'Square Pharmaceuticals PLC',
                'company_address'   => 'Pabna',
                'nominee_name'      => 'Shiti Biswas',
                'relationship'      => 'Spouse',
                'nominee_mobile'    => '01766624516',
                'nominee_address'   => 'Sreekundi, Magura',
                'opinion'           => 'Just keep it up',
                'suggestion'        => 'Seems okay',
            ],
            [
                'full_name'         => 'Md. Meraz Hossain',
                'shares'            => 1,
                'email'             => 'meraz.hossain@mutualtrustbank.com',
                'permanent_address' => 'Kashinathpur, Ward-1, Magura Sadar, Magura',
                'present_address'   => 'Gulshan-1, Dhaka',
                'phone'             => '01873730707',
                'profession'        => 'Banker',
                'company_name'      => 'Mutual Trust Bank PLC',
                'company_address'   => '26, Gulshan Avenue, Dhaka',
                'nominee_name'      => 'Mst. Mithila Biswas',
                'relationship'      => 'Spouse',
                'nominee_mobile'    => '01314521185',
                'nominee_address'   => 'Kashinathpur, Magura Sadar, Magura',
                'opinion'           => 'Going good',
                'suggestion'        => 'Mutual trust to be developed with a consistent way',
            ],
            [
                'full_name'         => 'Faiad Iftikhar Rafee',
                'shares'            => 2,
                'email'             => 'iamrafee@gmail.com',
                'permanent_address' => 'House 314, Village Parla, Magura',
                'present_address'   => 'Flat C2, Building 3, Rose Garden Tower, 244 Uttar Kalshi, Mirpur 12, Dhaka',
                'phone'             => '01911905373',
                'profession'        => 'Consultant',
                'company_name'      => 'BGD e-GOV CIRT',
                'company_address'   => '12th floor, Plot E-14/X, ICT Tower, Dhaka 1207',
                'nominee_name'      => 'Ani Shikder',
                'relationship'      => 'Wife',
                'nominee_mobile'    => '01796073105',
                'nominee_address'   => 'Flat C2, Rose Garden Tower, Mirpur 12, Dhaka',
                'opinion'           => 'A great initiative for future investment. Everyone needs to be honest and transparent.',
                'suggestion'        => 'Financial report should be shared with every member via email each month. Every member\'s opinion should be given priority in all decisions.',
            ],
            [
                'full_name'         => 'Sadeeque Al Mahadi',
                'shares'            => 1,
                'email'             => 'mahadimahi7@gmail.com',
                'permanent_address' => 'Village: Belnagor, Post: Magura, Thana: Magura Sadar',
                'present_address'   => 'Sadhinota Sarani, North Badda, Dhaka',
                'phone'             => '01708497371',
                'profession'        => 'Banker',
                'company_name'      => 'Brac Bank PLC',
                'company_address'   => 'Anik Tower, Tejgaon-Gulshan link road 220/B, Dhaka 1208',
                'nominee_name'      => 'Md. Abdul Khaleque',
                'relationship'      => 'Father',
                'nominee_mobile'    => '01673765718',
                'nominee_address'   => 'Village: Belnagor, Post: Magura, Thana: Magura Sadar',
                'opinion'           => null,
                'suggestion'        => null,
            ],
            [
                'full_name'         => 'Md Nimul Islam Badhon',
                'shares'            => 1,
                'email'             => 'mdbadhonkhanbadhon@gmail.com',
                'permanent_address' => 'Parnanduali, Magura Sador',
                'present_address'   => 'Nikunjo2, Khilhet Dhaka',
                'phone'             => '01920024743',
                'profession'        => 'Job holder (Merchandiser)',
                'company_name'      => 'Radisson Casual',
                'company_address'   => 'Sector 4, Uttara',
                'nominee_name'      => 'Md Monirul Islam',
                'relationship'      => 'Father',
                'nominee_mobile'    => '01717806517',
                'nominee_address'   => 'Parnanduali, Magura Sador',
                'opinion'           => null,
                'suggestion'        => null,
            ],
            [
                'full_name'         => 'Wahiduzzaman Hridoy',
                'shares'            => 2,
                'email'             => 'hridoy43@gmail.com',
                'permanent_address' => 'Ansar Colony, Pashu Hospital Para, Magura',
                'present_address'   => 'H-10, Block-2/c, Road-09, Pallabi S/A, Dhaka',
                'phone'             => '01727665348',
                'profession'        => 'Software Engineer',
                'company_name'      => 'Truely',
                'company_address'   => 'Central Region, Singapore',
                'nominee_name'      => 'Jannatul Ferdous',
                'relationship'      => 'Wife',
                'nominee_mobile'    => '01756080809',
                'nominee_address'   => 'Ansar Colony, Pashu Hospital Para, Magura',
                'opinion'           => 'Better to use WhatsApp for communication, Google Drive for file management, developing an investment management platform',
                'suggestion'        => 'Share policies with all members, monthly report and investment summary accessible to members, publish half-yearly or yearly public report',
            ],
            [
                'full_name'         => 'Md. Jubaer Hossain',
                'shares'            => 1,
                'email'             => 'jubaerkuet@gmail.com',
                'permanent_address' => 'Doar par, Magura',
                'present_address'   => '16/1/1 Tolarbagh, Mirpur 1, Dhaka 1216',
                'phone'             => '01754633041',
                'profession'        => 'Software Engineer',
                'company_name'      => 'Akij iBOS Ltd.',
                'company_address'   => '6/2 Kazi Nazrul Islam Rd, Dhaka 1207',
                'nominee_name'      => 'Rebeka Ikhtiar',
                'relationship'      => 'Mother',
                'nominee_mobile'    => '01789835193',
                'nominee_address'   => 'Doar par, Magura',
                'opinion'           => null,
                'suggestion'        => null,
            ],
            [
                'full_name'         => 'Hussain Muhammad Abid',
                'shares'            => 2,
                'email'             => 'hmabid1971@gmail.com',
                'permanent_address' => 'Holding 165, M.R. Road, Council Para, Magura',
                'present_address'   => 'Holding 165, M.R. Road, Council Para, Magura',
                'phone'             => '01841440924',
                'profession'        => 'Business',
                'company_name'      => 'Self employed',
                'company_address'   => 'Holding 165, M.R. Road, Council Para, Magura',
                'nominee_name'      => 'Afiya Shadman Aysha',
                'relationship'      => 'Spouse',
                'nominee_mobile'    => '01533925691',
                'nominee_address'   => 'Holding 165, M.R. Road, Council Para, Magura',
                'opinion'           => null,
                'suggestion'        => null,
            ],
            [
                'full_name'         => 'Md. Rubel Hasan',
                'shares'            => 1,
                'email'             => 'rubelhasanrony94@gmail.com',
                'permanent_address' => 'Kashinathpur, Magura Sadar, Magura',
                'present_address'   => 'Kashinathpur, Magura Sadar, Magura',
                'phone'             => '01789145849',
                'profession'        => 'Govt. Employee',
                'company_name'      => 'Upazila Health Complex, Shalikha, Magura',
                'company_address'   => 'UHC, Shalikha, Magura',
                'nominee_name'      => 'Md. Abdur Razzak',
                'relationship'      => 'Father',
                'nominee_mobile'    => '01922092989',
                'nominee_address'   => 'Kashinathpur, Magura Sadar, Magura',
                'opinion'           => null,
                'suggestion'        => null,
            ],
        ];

        foreach ($members as $data) {
            $member = Member::create([
                'full_name'         => $data['full_name'],
                'email'             => $data['email'],
                'phone'             => $data['phone'],
                'permanent_address' => $data['permanent_address'],
                'present_address'   => $data['present_address'],
                'profession'        => $data['profession'],
                'company_name'      => $data['company_name'],
                'company_address'   => $data['company_address'],
                'status'            => 'active',
            ]);

            Nominee::create([
                'member_id'    => $member->id,
                'nominee_name' => $data['nominee_name'],
                'relationship' => $data['relationship'],
                'mobile'       => $data['nominee_mobile'],
                'address'      => $data['nominee_address'],
            ]);

            Share::create([
                'member_id'        => $member->id,
                'number_of_shares' => $data['shares'],
                'total_amount'     => $data['shares'] * 2000,
                'status'           => 'pending',
            ]);

            if ($data['opinion'] || $data['suggestion']) {
                GroupOpinion::create([
                    'member_id'  => $member->id,
                    'opinion'    => $data['opinion'],
                    'suggestion' => $data['suggestion'],
                ]);
            }

            User::create([
                'name'      => $member->full_name,
                'email'     => $member->email,
                'password'  => Hash::make('agrojatra09'),
                'member_id' => $member->id,
            ]);
        }
    }
}
